export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";

export const USER_AUTO_LOGIN = "USER_AUTO_LOGIN";
export const USER_AUTO_LOGIN_SUCCESS = "USER_AUTO_LOGIN_SUCCESS";
export const USER_AUTO_LOGIN_ERROR = "USER_AUTO_LOGIN_ERROR";

export const USER_LOG_OUT = "USER_LOG_OUT";
export const USER_LOG_OUT_SUCCESS = "USER_LOG_OUT_SUCCESS";
export const USER_LOG_OUT_ERROR = "USER_LOG_OUT_ERROR";
