export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";

export const USER_AUTO_LOGIN = "USER_AUTO_LOGIN";
export const USER_AUTO_LOGIN_SUCCESS = "USER_AUTO_LOGIN_SUCCESS";
export const USER_AUTO_LOGIN_ERROR = "USER_AUTO_LOGIN_ERROR";

export const USER_LOG_OUT = "USER_LOG_OUT";
export const USER_LOG_OUT_SUCCESS = "USER_LOG_OUT_SUCCESS";
export const USER_LOG_OUT_ERROR = "USER_LOG_OUT_ERROR";

export const REG_USER = "REG_USER";
export const REG_USER_SUCCESS = "REG_USER_SUCCESS";
export const REG_USER_ERROR = "REG_USER_ERROR";

export const EDIT_USER = "EDIT_USER";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
export const EDIT_USER_ERROR = "EDIT_USER_ERROR";

export const GET_TREE = "GET_TREE";
export const GET_TREE_SUCCESS = "GET_TREE_SUCCESS";
export const GET_TREE_ERROR = "GET_TREE_ERROR";

export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";

export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR";

export const ACTIVATE_USER = "ACTIVATE_USER";
export const ACTIVATE_USER_SUCCESS = "ACTIVATE_USER_SUCCESS";
export const ACTIVATE_USER_ERROR = "ACTIVATE_USER_ERROR";
